### ISSUE TITLE
docker build 후 container 상에서 java 경로를 찾을 수 없다고 나오는 현상

### ISSUE THREAD

**Issue by donghyukc** [nota-github/np_app_text_retrieval_inference#5]
* Dockerfile의 다음 명령어를 Container상에서 별도로 실행해준 다음 해결. 
  * ln -sf ${APP_PATH}/jdk-20.0.1/bin/java /opt/conda/bin/java

**Comment by lifelongeeek** [comment]
PR https://github.com/nota-github/np_app_text_retrieval_inference/pull/6 에서 해결되어 이슈 종료
